# c) Avatar (movie) network (undirected, weighted)

- Nodes are characters. 
- Links represent a same-scene appearance between two characters in the moviea
- the weight gives the number of same-scene appearance.


*Source: J. Kaminski et al., "Moviegalaxies - Social Networks in Movies." https://doi.org/10.7910/DVN/T4HBA3, Harvard Dataverse, V3 (2018)*

In [1]:
import pandas as pd
from pathlib import Path

In [4]:
ROOT = Path.cwd().parent
DATA_DIR = ROOT/"data"

nodes_path = DATA_DIR/"nodes.csv"
edges_path = DATA_DIR/"edges.csv"

nodes = pd.read_csv(nodes_path)
edges = pd.read_csv(edges_path)

In [7]:
nodes.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Id        30 non-null     int64
 1   Label     30 non-null     str
 2   movie_id  30 non-null     int64
dtypes: int64(2), str(1)
memory usage: 852.0 bytes

In [6]:
nodes.head()

       Id      Label  movie_id
0  519631       JAKE        88
1  520100   QUARITCH        88
2  520425  SELFRIDGE        88
3  520314      GRACE        88
4  520156       NORM        88

In [9]:
edges.info()

<class 'pandas.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Source    105 non-null    int64
 1   Target    105 non-null    int64
 2   Type      105 non-null    str
 3   Id        105 non-null    int64
 4   Label     105 non-null    int64
 5   Weight    105 non-null    int64
 6   movie_id  105 non-null    int64
dtypes: int64(6), str(1)
memory usage: 5.9 KB

In [8]:
edges.head()

   Source  Target        Type  Id  Label  Weight  movie_id
0  519777  519783  Undirected   0  17872       1        88
1  519965  519631  Undirected   1  17876       1        88
2  519965  520084  Undirected   2  17877       1        88
3  519965  520010  Undirected   3  17875       1        88
4  522131  520314  Undirected   4  18043       1        88